### ISSUE TITLE
Update every days ? 

### ISSUE THREAD

**Issue by romquenin** [romeupalos/noip#1]
Hello, thanks for this awsome feature.

I would like to know why the image is updating every days during the night. 

Thanks.

**Comment by romeupalos** [comment]
Hello,

Thanks for your message!
That was done because it's not possible to get noip's current version in order to trigger a new build.
I intend to improve the travis job to get noip's version before pushing the images to docker hub.

This way, the images will only update if there is a new version, even though the travis job runs every day.

If you have some ideas/concerns, they are always welcome.

Thanks

**Comment by romeupalos** [comment]
Hello @romquenin,

I changed the code to generate the docker image if the noip client version has changed.
The build will run daily though, but it won't push the changes to the docker hub registry, hence I'm closing this issue.
