### ISSUE TITLE
Can't create config file

### ISSUE THREAD

**Issue by cguentherTUChemnitz** [romeupalos/noip#2]
everywhere i try to create a config file i get the following output by the container:

`Can't create config file (/usr/local/etc/no-ip2.conf)`

**Comment by romeupalos** [comment]
Thank you for letting me know.
Could you share the docker command you are using?

**Comment by davewentzel** [comment]
fwiw, I had to chmod 777 on the folder to get passed the error.  I don't know if that's the _right_ fix, but it works.  

Just wanna say thanks for this container.  The first 3 I tried didn't work for me and I thought were needlessly complicated.  Kudos to you sir!!!

**Comment by romeupalos** [comment]
@davewentzel 
What is the OS you are running.
I believe the issue happens because you are trying to save the file in a protected folder on your own local machine.

You can save the file in any directory that is owned by your user, but not on directories owned by the super user.

I'll improve the README.md file if you confirm that this is the issue.

**Comment by davew-msft** [comment]
ubuntu 16.04.

Yes, you are correct sir.  

I believe that is standard Docker behavior and a step I probably should've known.  

Thanks again sir.  Awesome work

**Comment by homerisback** [comment]
Hello,
Using provided docker command from github, I have the same issue under debian OMV5/docker, because root ownership, I presume.
I manually created no-ip2.conf empty file in /usr/local/etc, unfortunately it won't work either, reporting "no such file".

Maybe I could manually fill the conf file with my credentials @no-ip but I can't find any 'example' of conf file structure.
Would you have something to share or a better way to go ? Thanks !

**Comment by romeupalos** [comment]
@homerisback
Can you please confirm it one more time. By creating and empty file and setting permissions on it for other users to read and modify (`chmod 777`), it should work.
The actual intended why for the docker container to use is to have this file in a different folder in the host.
For instance:

1. Create the file /home/homerisback/noip/no-ip2.conf (`touch /home/homerisback/noip/no-ip2.conf`)
2. use this in the docker run: `-v /home/homerisback/noip/no-ip2.conf:/usr/local/etc/no-ip2.conf:rw`

If the above doesn't work, it means that the user from docker (UID: 1000) cannot write to this file.
Then you can run: `chmod 777 /home/homerisback/noip/no-ip2.conf` and then run the docker container again.

**Comment by dormancygrace** [comment]
Same problem here on Ubuntu 22 (oracle cloud image). Container works like a charm on Oracle Linux 8, but can`t make it work under Ubuntu. @romeupalos tried method above - without success
